import Foundation
import Testing
@testable import BlahDiem

@Suite struct KeyFileTests {
  let backend = TestBackend()

  func contents() async throws -> KeyFileContents {
    let root = try await IdentityPrivateKey.generate(.ed25519, using: backend)
    let device = try await DevicePrivateKey.generate(.ed25519, using: backend)
    let data = try UserProfile(home: Fixture.home(), domains: [ProfileDomain("keys.example")]).encoded()
    let identity = try await Identity(data: data, identityKey: root, deviceKey: device, using: backend)
    return try KeyFileContents(profile: identity.profile, keys: [
      KeyFilePrivateKey(publicKey: root.publicKey.key, secret: #require(root.rawRepresentation)),
      KeyFilePrivateKey(publicKey: device.publicKey.key, secret: #require(device.rawRepresentation)),
    ])
  }

  @Test func rfc9180DerivationMatchesIndependentHPKE() throws {
    let raw = try KeyFile.deriveP256PrivateKey([UInt8](repeating: 7, count: 32))
    #expect(raw.map { String(format: "%02x", $0) }.joined() ==
      "65d62bc8c3f8a15bbba263588dc0da0044aa60e64058d0f4a583d7e958a5440a")
  }

  @Test func recoveryDeviceAndCombinedFilesAuthenticateTheirContents() async throws {
    let contents = try await contents()
    let recipient = try await backend.makeEncryptionKey(.p256)
    for keys in [[contents.keys[0]], [contents.keys[1]], contents.keys] {
      let payload = try KeyFileContents(profile: contents.profile, keys: keys)
      let file = try await KeyFile.seal(payload, salt: Array(repeating: 3, count: 16),
        to: recipient.publicKey, using: backend)
      let opened = try await KeyFile(encoding: file.encoding).open(with: recipient, using: backend)
      #expect(opened.encoding == payload.encoding)
      let another = try await backend.makeEncryptionKey(.p256)
      await #expect(throws: DiemError.decryptionFailed) { try await file.open(with: another, using: backend) }
      for field in [UInt64(2), 3, 7, 8] {
        var record = try CBOR(decoding: file.encoding).recordValue(requiredKeys: 0..<9)
        var bytes = try record[field]!.bytesValue()
        bytes[bytes.count - 1] ^= 1
        record[field] = .bytes(bytes)
        await #expect(throws: (any Error).self) {
          try await KeyFile(encoding: CBOR.record(record).encoded).open(with: recipient, using: backend)
        }
      }
      // Even an otherwise accepted unknown header field belongs to the HPKE context.
      var record = try CBOR(decoding: file.encoding).recordValue(requiredKeys: 0..<9)
      record[99] = .text("untrusted addition")
      await #expect(throws: (any Error).self) {
        try await KeyFile(encoding: CBOR.record(record).encoded).open(with: recipient, using: backend)
      }
    }
  }

  @Test func malformedMismatchedAndLegacyFilesFail() async throws {
    let contents = try await contents()
    let wrong = try KeyFilePrivateKey(publicKey: contents.keys[0].publicKey, secret: Array(repeating: 1, count: 32))
    let payload = try KeyFileContents(profile: contents.profile, keys: [wrong])
    await #expect(throws: DiemError.identityMismatch) { try await payload.validate(using: backend) }
    #expect(throws: (any Error).self) { try KeyFile(encoding: Array("{\"version\":1}".utf8)) }
    #expect(throws: (any Error).self) { try KeyFile(encoding: Array(repeating: 0, count: KeyFile.maximumBytes + 1)) }
    #expect(throws: DiemError.invalidKey) {
      try KeyFileContents(profile: contents.profile, keys: [contents.keys[0], contents.keys[0]])
    }
  }

  @Test func passwordIsRequiredButOneCharacterAndExactUnicodeAreAccepted() async throws {
    for password in ["x", " ", "é", "e\u{301}"] {
      _ = try await KeyFile.passwordRecipient(password, salt: Array(repeating: 3, count: 16), using: backend) { bytes, salt, rounds in
        #expect(bytes == Array(password.utf8))
        #expect(salt.count == 16 && rounds == 600_000)
        return Array(repeating: 7, count: 32)
      }
    }
    await #expect(throws: DiemError.invalidKey) {
      try await KeyFile.passwordRecipient("", salt: Array(repeating: 3, count: 16), using: backend) { _, _, _ in
        Issue.record("An empty password reached PBKDF2")
        return []
      }
    }
  }

  @Test func expiredSignedProfilesRemainRecoverable() async throws {
    let contents = try await contents()
    backend.advance(by: 366 * 86400)
    try await contents.validate(using: backend)
    await #expect(throws: (any Error).self) { try await contents.profile.verify(using: backend) }
  }

  @Test func nativeAndBrowserInteroperability() async throws {
    // PBKDF2-HMAC-SHA256("x", 16 bytes of 3, 600000, 32), independently generated by Node.
    let material: [UInt8] = [9,27,162,112,60,163,49,203,154,182,230,154,195,175,191,94,
      116,212,168,252,236,253,84,175,161,112,243,165,0,84,179,50]
    let recipient = try await KeyFile.passwordRecipient("x", salt: Array(repeating: 3, count: 16), using: backend) { _, _, _ in material }
    struct Vector: Codable { let file: [UInt8] }
    if let output = ProcessInfo.processInfo.environment["BLAH_KEY_FILE_VECTOR"] {
      let file = try await KeyFile.seal(contents(), salt: Array(repeating: 3, count: 16), to: recipient.publicKey, using: backend)
      try JSONEncoder().encode(Vector(file: file.encoding)).write(to: URL(fileURLWithPath: output))
    }
    let directory = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
      .deletingLastPathComponent().appendingPathComponent("Web/tests")
    for name in ["key-file-native.json", "key-file-browser.json"] {
      let url = directory.appendingPathComponent(name)
      if ProcessInfo.processInfo.environment["BLAH_KEY_FILE_VECTOR"] != nil && !FileManager.default.fileExists(atPath: url.path) { continue }
      let vector = try JSONDecoder().decode(Vector.self, from: Data(contentsOf: url))
      let file = try KeyFile(encoding: vector.file)
      let contents = try await file.open(with: recipient, using: backend)
      #expect(contents.keys.count == 2)
      #expect(try AnyBlahProfile(contents.profile).domains == ["keys.example"])
    }
  }
}
